# -*- coding: utf-8 -*-
"""FPML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJ-PMsoXCbc7eF5UTxX_Pi0zKuFapMKk

Sabib Prastio
22.12.2598
"""

import pandas as pd
import matplotlib.pyplot as plt
import joblib

from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)

from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    StratifiedKFold,
    RandomizedSearchCV
)

from sklearn.preprocessing import LabelEncoder

# Membaca Dataset
df = pd.read_csv("student-lifestyle-and-stress-dataset.csv")

print("5 Data Pertama")
print(df.head())

print("\nUkuran Dataset")
print(df.shape)

print("\nInformasi Dataset")
print(df.info())

# Mengecek Missing Value
print("\nMissing Value")
print(df.isnull().sum())

# Mengecek Data Duplikat
print("\nJumlah Data Duplikat :", df.duplicated().sum())

# Encoding Data Kategorikal
encoders = {}

for col in df.select_dtypes(include="object").columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

print("\nDataset Setelah Encoding")
print(df.head())

# Memisahkan Fitur dan Target
X = df.drop("Stress_Level", axis=1)
y = df["Stress_Level"]

# Mengisi missing value menggunakan median
imputer = SimpleImputer(strategy="median")

X = pd.DataFrame(
    imputer.fit_transform(X),
    columns=X.columns
)

# Membagi Data Training dan Testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)
print("\nJumlah Data Training :", X_train.shape)
print("Jumlah Data Testing :", X_test.shape)

# Membangun Model Random Forest
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt'],
    'class_weight': [None, 'balanced']
}

random = RandomizedSearchCV(
    RandomForestClassifier(random_state=42),
    param_distributions=param_grid,
    n_iter=20,
    cv=5,
    scoring='accuracy',
    random_state=42,
    n_jobs=-1,
    verbose=2
)

random.fit(X_train, y_train)

print("===== HASIL RANDOMIZED SEARCH =====")
print("Best Parameters:")
print(random.best_params_)

print("\nBest Cross Validation Accuracy:")
print(round(random.best_score_, 4))

rf = random.best_estimator_

joblib.dump(rf, "model.pkl")
joblib.dump(imputer, "imputer.pkl")
joblib.dump(encoders, "encoders.pkl")

# Prediksi
y_pred = rf.predict(X_test)

# Evaluasi Model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall = recall_score(y_test, y_pred, zero_division=0)
f1 = f1_score(y_test, y_pred, zero_division=0)

print("\n===== HASIL EVALUASI =====")
print("Accuracy :", round(accuracy, 4))
print("Precision:", round(precision, 4))
print("Recall   :", round(recall, 4))
print("F1-Score :", round(f1, 4))

# Menghitung probabilitas prediksi
prob = rf.predict_proba(X_test)[:,1]

# Menghitung nilai ROC-AUC
roc = roc_auc_score(y_test, prob)

print("ROC AUC :", roc)

# Classification Report
print("\nClassification Report")
print(classification_report(y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix")
print(cm)

# Visualisasi Confusion Matrix
plt.figure(figsize=(5, 4))
plt.imshow(cm, cmap="Blues")

plt.title("Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")

plt.xticks([0,1])
plt.yticks([0,1])

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(
            j,
            i,
            cm[i, j],
            ha="center",
            va="center",
            color="black"
        )

plt.colorbar()
plt.show()

# Feature Importance
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print("\nFeature Importance")
print(importance)

# Visualisasi Feature Importance
plt.figure(figsize=(8, 5))

plt.barh(
    importance["Feature"],
    importance["Importance"]
)

plt.title("Feature Importance Random Forest")
plt.xlabel("Importance")
plt.gca().invert_yaxis()

plt.show()

# 10-Fold Cross Validation
cv = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)

scores = cross_val_score(
    rf,
    X,
    y,
    cv=cv,
    scoring="accuracy"
)

print("\n===== 10-Fold Cross Validation =====")
print("Accuracy setiap fold")
print(scores)

print("\nMean Accuracy :", round(scores.mean(), 4))
print("Std Accuracy  :", round(scores.std(), 4))

# Ringkasan Hasil
print("\n===== RINGKASAN =====")

print(f"Accuracy                 : {accuracy:.4f}")
print(f"Precision                : {precision:.4f}")
print(f"Recall                   : {recall:.4f}")
print(f"F1-Score                 : {f1:.4f}")
print(f"Mean 10-Fold Accuracy    : {scores.mean():.4f}")
print(f"Standar Deviasi Accuracy : {scores.std():.4f}")